#!/bin/bash

echo "(* THIS FILE WAS AUTOMATICALLY GENERATED BY CAT'ING LIBRARY SOURCES *)"
echo '[@@@ocaml.warning "-27-32-35"]' # so it builds with default dune settings

for module in $(ocamldep ../src/*.ml -sort); do

modname=$(basename "$module" .ml)
modname=${modname^}
iface="${module%.ml}.mli"

if [ -f "$iface" ]; then
echo "module ${modname} : sig
$(cat $iface)
end = struct
$(cat $module)
end"

else
echo "module ${modname} = struct
$(cat $module)
end"
fi

done
